<?php

$labels['compose_encrypted'] = 'Schreiben und verschlüsseln';
$labels['compose_encrypted_title'] = 'Neue Nachricht schreiben und beim Versand verschlüsseln';
$labels['encrypt_and_send'] = 'Verschlüsseln und senden';
$labels['reply_encrypted'] = 'Verschlüsselt antworten';
$labels['reply_encrypted_title'] = 'Antwort verfassen und verschlüsseln';
$labels['forward_encrypted'] = 'Verschlüsselt weiterleiten';
$labels['forward_encrypted_title'] = 'Verschlüsseln und weiterleiten';

$messages['sending_only_after_recipient_check'] = 'Versand erst nach Empfänger-Prüfung möglich';
$messages['no_key_for_address'] = 'Kein Schlüssel für %s vorhanden.';
$messages['found_importable_keys'] = "Posteo hat öffentliche Schlüssel der folgenden E-Mail-Adressen für den Import in Mailvelope gefunden:";
$messages['found_importable_sender_key'] = "Posteo hat einen öffentlichen Schlüssel Ihrer E-Mail-Adresse für den Import in Mailvelope gefunden:";
$messages['found_importable_sender_key_suffix'] = "oder einen Schlüssel manuell importieren";
$messages['found_verified_keys'] = "Posteo hat verifizierte öffentliche Schlüssel der folgenden E-Mail-Adressen für den Import in Mailvelope gefunden:";
$messages['found_verified_sender_key'] = "Posteo hat einen verifizierten öffentlichen Schlüssel Ihrer E-Mail-Adresse für den Import in Mailvelope gefunden:";
$messages['import'] = "hinzufügen";
$messages['no_keys_found'] = "Bitte entfernen Sie die folgenden Empfänger oder importieren Sie deren öffentliche Schlüssel manuell:";
$messages['no_sender_keys_found'] = "Automatisch konnte kein öffentlicher Schlüssel für Ihre E-Mail-Adresse gefunden werden, bitte importieren Sie Ihren Schlüssel manuell.";
$messages['switch_on_api'] = "Um die Verwendung von Mailvelope mit Posteo zu verbessern aktivieren sie bitte die Mailvelope-API für Posteo: <strong>Mailvelope -> Optionen -> Optionen -> Liste der E-Mail-Anbieter -> posteo.de</strong>";
$messages['point_to_modern_skins'] = "Die Verwendung von Mailvelope wird in dem Classic-Oberflächendesign nicht unterstützt. Bitte wählen sie ein modernes Oberflächendesign aus.";
$messages['quote_header_reply'] = '%s schrieb:';
$messages['quote_header_forward'] = '----- Weitergeleitete Nachricht von %s -----';
$messages['bcc_not_empty_error'] = 'Bcc wird beim verschlüsselten Senden nicht unterstützt, bitte entfernen Sie die Adressen.';
