<?php

$labels['compose_encrypted'] = 'Compose and encrypt';
$labels['compose_encrypted_title'] = 'Compose new message and send encrypted.';
$labels['encrypt_and_send'] = 'Encrypt and send';
$labels['reply_encrypted'] = 'Reply encrypted';
$labels['reply_encrypted_title'] = 'Reply with encryption';
$labels['forward_encrypted'] = 'Forward encrypted';
$labels['forward_encrypted_title'] = 'Forward with encryption';

$messages['sending_only_after_recipient_check'] = 'Sending will be enabled when all recipients have been successfully checked for public keys.';
$messages['no_key_for_address'] = 'No key found for %s.';
$messages['found_importable_keys'] = "Posteo has found public keys for import to Mailvelope for the following email addresses: %s";
$messages['found_importable_sender_key'] = "Posteo has found a public key for your emails address to import to Mailvelope:";
$messages['found_importable_sender_key_suffix'] = "or import a key manually";
$messages['found_verified_keys'] = "Posteo has found a verified public key to import to Mailvelope for the following addresses: %s";
$messages['found_verified_sender_key'] = "Posteo has found a verified public key for your email address to import to Mailvelope:";
$messages['import'] = "import";
$messages['no_keys_found'] = "Please remove the following recipients or import their public keys manually.";
$messages['no_sender_keys_found'] = "A public key for your email address could not automatically be found. Please import your key manually.";
$messages['switch_on_api'] = "To improve your encryption experience switch on the Mailvelope-API for posteo.de: <strong>Mailvelope -> Options -> Options -> List of Mail Providers -> posteo.de</strong>";
$messages['point_to_modern_skins'] = "Using Mailvelope isn't supported with this skin. Please choose another skin for an improved experience of using Mailvelope with Posteo";
$messages['quote_header_reply'] = '%s wrote:';
$messages['quote_header_forward'] = '----- Forwarded message from %s -----';
$messages['bcc_not_empty_error'] = 'Bcc is not supported with encrypted sending, please remove the addresses.';
